### PR TITLE
Dec2024 updates

### PR DESCRIPTION
**Pull request by jrwashburn**
Article 2 
- [x] English-speaking lead requirement
https://forum.autonomys.xyz/t/on-english-speaking-lead-ambassadors/4519
- [x] Remove requirement to run a farmer
https://forum.autonomys.xyz/t/must-all-ambassadors-run-a-node/4350
- [x] Remove requirement for 2/3rds attendance  
https://forum.autonomys.xyz/t/governance-poll-attendance/4636
- [x] Update definition of failure to participate
https://discord.com/channels/864285291518361610/1119036435496972358/1285574381556203626
(could not find on Forum) 

Article 4
- [x] Conflict Resolution Team recusal, appellate CRT, private deliberations
https://forum.autonomys.xyz/t/conflict-resolution-team-crt-procedures-for-handling-complaints/4604

Housekeeping
- [x] added links to readme, add .gitignore

### CODE REVIEW

**Review by jrwashburn — COMMENTED** [review]
Sumbitting for approval. Looks good to me!

**Review by jrwashburn — COMMENTED** [review]
Fixed merge conflict

**Comment by jrwashburn** [comment]
Updated with repeal language. backstory:

Jonathan — Today at 3:35 PM
@Jim - Autonomys FYI, PR has been submitted with all of the 2024-approved bylaw modifications.
I'm not sure about how I handle the two that are deletions - I marked them up for strike-through vs. just deleting since that may change numbers. It may be better to just delete the text but leave the "intentionally blank" placeholders... I think that might be better. But wanted an opinion so left it like this for now, please comment on review. And remember to turn off whitespace!
For anyone curious, or who wants to validate / follow-along, please see: https://github.com/autonomys-ambassadors/bylaws/pull/4
@Fradique - Autonomys I could not find the form post for the vot on failure to participate, so I just linked the discord post. If it is there but I missed it, please let me know. (Referring to the forum-equivalent for: ⁠🏘⏐amb-governance⁠)
vexr — Today at 4:21 PM
If you're seeking opinions, I believe keeping the placeholders is essential, particularly since there appear to be multiple versions of the bylaws circulating. A format like Article 2, Section 2(e): Repealed on November xx, 2024 works well. Would it also be beneficial to include the date of the last revision (of the bylaws) directly on the bylaws for clarity? 
Jonathan — Today at 5:42 PM
The source is in HTML, so the placeholder number/letter are dependent on renderer at some level.
Jim - Autonomys — Today at 5:43 PM
Modifications look in keeping with the agreed upon amendments. If anyone wants to view the changes without whitespace you can use this link which cuts out all the noise: https://github.com/autonomys-ambassadors/bylaws/pull/4/files?w=1

I came here to say something about the intentionally blank and then saw @vexr's comment below. I also thought adding the exact clause would help anyone looking for it if it were referenced externally - confirmation the reader is in the right place,

The repealed language does work well too IMO. I think with that and the version control history we could delete rather than strikethrough.
Jonathan — Today at 5:45 PM
I like the repealed suggestion. I'll make chagnes. 

I wouldn't think we need a date since it is in git ... but it doesn't hurt either. Just have to remember to update it, and it would be the date of the submission, not the merge approval, so it would end up pre-dating whatever git will show for the merge.
Anyone opposed to me copy/pasting this into git comments too?
Jim - Autonomys — Today at 5:48 PM
Yeah, we should have had this discussion on GitHub 🙂

**Review by jim-counter — APPROVED** [review]
LGTM!

**Pull request merged**
